## Classification 

In [1]:
import pandas as pd
import numpy as np
import json
import collections 
import matplotlib.pyplot as plt
import itertools

import re
import nltk
import gensim

### prepare training data

In [2]:
# get training data

col_list= ['topic','advert_label']
train_all_a = pd.read_csv("sample_train_class(final).csv")
train_a = pd.read_csv("sample_train_class(final).csv",usecols=col_list)


train_all_b = pd.read_csv("sample_train_class2(final).csv")
train_b = pd.read_csv("sample_train_class2(final).csv",usecols=col_list)

comb = [train_a, train_b]
comb_all = [train_all_a, train_all_b]

comb_train = pd.concat(comb)
comb_train_all=pd.concat(comb_all)

print(len(comb_train))

#comb_train_all.to_csv('sample_traincombined_class(final).csv',index=False)


600


In [ ]:
# to see full column content instead of truncated text
pd.set_option('display.max_colwidth', -1)

# first x rows
print(comb_train.head(10))


In [4]:
train_text  = comb_train['topic']
print(train_text.head())

0    ['finally', 'got', 'monitor', 'arm', 'setup', 'party', 'bonus', 'point', 'best', 'one', 'ever', 'check', 'lineup']                                                                                                    
1    ['focus', 'physical', 'fitness', 'important', 'dr', 'dina', 'gentile', 'author', 'athletic', 'administrator', 'share', 'creative', 'way', 'use', 'online', 'platform', 'keep', 'athlete', 'motivated', 'engaged', 'h']
2    ['new', 'job', 'senior', 'brand', 'designer']                                                                                                                                                                         
3    ['picture']                                                                                                                                                                                                           
4    ['productive', 'fromhome', 'coach', 'mizpah', 'start', 'prayer', 'list', 'listen', 'inspirational', 'podcast']     

In [5]:
#code to convert df to list 

token = comb_train['topic'].tolist()
#print(token)

def convert(lst): 
    return eval(lst)

final=[]
for i in token:
    tokenf=convert(i)
    final.append(tokenf)

print(final)

[['finally', 'got', 'monitor', 'arm', 'setup', 'party', 'bonus', 'point', 'best', 'one', 'ever', 'check', 'lineup'], ['focus', 'physical', 'fitness', 'important', 'dr', 'dina', 'gentile', 'author', 'athletic', 'administrator', 'share', 'creative', 'way', 'use', 'online', 'platform', 'keep', 'athlete', 'motivated', 'engaged', 'h'], ['new', 'job', 'senior', 'brand', 'designer'], ['picture'], ['productive', 'fromhome', 'coach', 'mizpah', 'start', 'prayer', 'list', 'listen', 'inspirational', 'podcast'], ['employee', 'put', 'brake', 'returning', 'officesnearly', 'half', 'permanently', 'agility', 'pr', 'solution'], ['definitely', 'agree', 'inspiring', 'book', 'read', 'hard', 'time'], ['two', 'assistant', 'mr', 'scraggles', 'princess', 'chloenotice', 'ive', 'tie', 'window', 'handle', 'open', 'window'], ['race', 'exit', 'virtual', 'meeting', 'appropriate', 'speed', 'remains', 'real'], ['done', 'really'], ['high', 'fived', 'way', 'fast', 'five', 'game'], ['disparate', 'information', 'creates', 

In [6]:
#Code to covert docs to vec
def docs2vecs(docs, dictionary):
    vecs1 = [dictionary.doc2bow(doc) for doc in docs]
    return vecs1

In [7]:
#create dictionary and vectors for documents

from gensim import corpora
tweet_dictionary = gensim.corpora.Dictionary(final)
tweet_vecs = docs2vecs(final, tweet_dictionary)

print(tweet_dictionary)
print(tweet_vecs[2])

Dictionary(2511 unique tokens: ['arm', 'best', 'bonus', 'check', 'ever']...)
[(34, 1), (35, 1), (36, 1), (37, 1), (38, 1)]


In [8]:
## save dictionary 

tweet_dictionary.save('class_dict')

In [9]:
#covert label into list

label=comb_train['advert_label'].tolist()
#print(label)

In [10]:
#Label the trained data. 

#convert to dict with the term ids given frequency 1
all_data_as_dict = [{id:1 for (id, tf_value) in vec} for vec in tweet_vecs]
print(type(all_data_as_dict))
print (all_data_as_dict[0])

#create tuples
labeled_data = list(zip(all_data_as_dict, label))

print(labeled_data[5])

<class 'list'>
{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1, 11: 1, 12: 1}
({50: 1, 51: 1, 52: 1, 53: 1, 54: 1, 55: 1, 56: 1, 57: 1, 58: 1, 59: 1}, 'advert ')


### build NLTK NaiveBayes classifier as a trial

In [18]:
#Generate the trained classifier
classifier = nltk.NaiveBayesClassifier.train(labeled_data)

### prepare test data

In [11]:
# get test data

col_list= ['topic','advert_label']
test_all = pd.read_csv("sample_test_class(final).csv")

test= pd.read_csv("sample_test_class(final).csv",usecols=col_list)

print(len(test_all))
print(len(test_all))

150
150


In [12]:
test_text  = test['topic']
print(test_text.head())

0    ['tech', 'giant', 'twitter', 'allowing', 'employee', 'forever', 'checkout', 'insightful', 'piece']                                                                                                              
1    ['pretty', 'productive', 'tuesday', 'morning', 'also', 'realized', 'neglecting', 'project', 'sometimes', 'hard', 'keep', 'track', 'everything', 'day', 'keep', 'running', 'together', 'even', 'project', 'list']
2    ['lextalk', 'world', 'clickaway', 'creator', 'pleased', 'conversation', 'mr', 'girish', 'viswanathan', 'landmark', 'group', 'watch']                                                                            
3    ['good', 'pod', 'upnp', 'nothin', 'c', 'downplaying', 'dhs', 'advisory', 'name', 'researcher']                                                                                                                  
4    ['enjoying', 'bank', 'holiday', 'sunshine', 'garden', 'explore', 'key', 'tip', 'transition', 'help', 'team', 'successfully']               

In [13]:
#code to convert df to list 

token1 = test['topic'].tolist()
#print(token)

def convert(lst): 
    return eval(lst)

final1=[]
for i in token1:
    tokenf=convert(i)
    final1.append(tokenf)

print(final1)

[['tech', 'giant', 'twitter', 'allowing', 'employee', 'forever', 'checkout', 'insightful', 'piece'], ['pretty', 'productive', 'tuesday', 'morning', 'also', 'realized', 'neglecting', 'project', 'sometimes', 'hard', 'keep', 'track', 'everything', 'day', 'keep', 'running', 'together', 'even', 'project', 'list'], ['lextalk', 'world', 'clickaway', 'creator', 'pleased', 'conversation', 'mr', 'girish', 'viswanathan', 'landmark', 'group', 'watch'], ['good', 'pod', 'upnp', 'nothin', 'c', 'downplaying', 'dhs', 'advisory', 'name', 'researcher'], ['enjoying', 'bank', 'holiday', 'sunshine', 'garden', 'explore', 'key', 'tip', 'transition', 'help', 'team', 'successfully'], ['bos', 'really', 'need', 'staying', 'logged', 'still', 'give', 'look', 'lol'], ['pixel', 'international', 'group', 'using', 'glad', 'welcome', 'board', 'request', 'free', 'month', 'trial'], ['ooo', 'texas', 'heat', 'gonna', 'tan', 'potato'], ['learn', 'really', 'team'], ['business', 'owner', 'realizing', 'flexible', 'workforce', '

In [14]:
#create  vectors for documents uusing dictionary in training dataset

tweet_vecs_test = docs2vecs(final1, tweet_dictionary)

print(tweet_vecs_test[0])

[(52, 1), (221, 1), (953, 1), (1957, 1), (2369, 1)]


In [15]:
#covert label into list

label_test=test['advert_label'].tolist()
#print(label_test)

In [16]:
#Label the test data. 

#convert to dict with the term ids given frequency 1
all_data_as_dict1 = [{id:1 for (id, tf_value) in vec} for vec in tweet_vecs_test]
print(type(all_data_as_dict1))
print (all_data_as_dict1[0])

#create tuples
labeled_data_test = list(zip(all_data_as_dict1, label_test))

print(labeled_data_test[0])

<class 'list'>
{52: 1, 221: 1, 953: 1, 1957: 1, 2369: 1}
({52: 1, 221: 1, 953: 1, 1957: 1, 2369: 1}, 'advert')


In [21]:
#check performance
print(nltk.classify.accuracy(classifier, labeled_data_test))

0.10666666666666667


In [23]:
## get precision, recall etc. 

import sklearn

test_result = []
gold_result = []

for i in range(len(labeled_data_test)):
    test_result.append(classifier.classify(labeled_data_test[i][0]))
    gold_result.append(labeled_data_test[i][1])

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix   

print('\nClasification report:\n', classification_report(gold_result, test_result))
print('\nConfussion matrix:\n',confusion_matrix(gold_result, test_result))


Clasification report:
               precision    recall  f1-score   support

      advert       0.52      0.12      0.20       107
     advert        0.00      0.00      0.00         0
  non-advert       0.43      0.07      0.12        43

    accuracy                           0.11       150
   macro avg       0.32      0.06      0.11       150
weighted avg       0.49      0.11      0.17       150


Confussion matrix:
 [[13 90  4]
 [ 0  0  0]
 [12 28  3]]


C:\Users\User\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


### Try different classifier methods

In [19]:
from nltk.classify.scikitlearn import SklearnClassifier

from sklearn.naive_bayes import MultinomialNB,BernoulliNB

from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.svm import SVC, LinearSVC



print("Original Naive Bayes Algo accuracy percent:", (nltk.classify.accuracy(classifier, labeled_data_test))*100)
#classifier.show_most_informative_features(15)

MNB_classifier = SklearnClassifier(MultinomialNB())
MNB_classifier.train(labeled_data)
print("MNB_classifier accuracy percent:", (nltk.classify.accuracy(MNB_classifier, labeled_data_test))*100)

BernoulliNB_classifier = SklearnClassifier(BernoulliNB())
BernoulliNB_classifier.train(labeled_data)
print("BernoulliNB_classifier accuracy percent:", (nltk.classify.accuracy(BernoulliNB_classifier, labeled_data_test))*100)

LogisticRegression_classifier = SklearnClassifier(LogisticRegression())
LogisticRegression_classifier.train(labeled_data)
print("LogisticRegression_classifier accuracy percent:", (nltk.classify.accuracy(LogisticRegression_classifier, labeled_data_test))*100)

SGDClassifier_classifier = SklearnClassifier(SGDClassifier())
SGDClassifier_classifier.train(labeled_data)
print("SGDClassifier_classifier accuracy percent:", (nltk.classify.accuracy(SGDClassifier_classifier, labeled_data_test))*100)

SVC_classifier = SklearnClassifier(SVC())
SVC_classifier.train(labeled_data)
print("SVC_classifier accuracy percent:", (nltk.classify.accuracy(SVC_classifier, labeled_data_test))*100)

LinearSVC_classifier = SklearnClassifier(LinearSVC())
LinearSVC_classifier.train(labeled_data)
print("LinearSVC_classifier accuracy percent:", (nltk.classify.accuracy(LinearSVC_classifier, labeled_data_test))*100)



Original Naive Bayes Algo accuracy percent: 10.666666666666668
MNB_classifier accuracy percent: 68.0
BernoulliNB_classifier accuracy percent: 74.0
LogisticRegression_classifier accuracy percent: 65.33333333333333
SGDClassifier_classifier accuracy percent: 61.33333333333333
SVC_classifier accuracy percent: 71.33333333333334
LinearSVC_classifier accuracy percent: 60.0


C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [20]:
final_classifier = BernoulliNB_classifier.train(labeled_data)

In [63]:
## get precision, recall of final classifier etc. 

import sklearn

test_result = []
gold_result = []

for i in range(len(labeled_data_test)):
    test_result.append(final_classifier.classify(labeled_data_test[i][0]))
    gold_result.append(labeled_data_test[i][1])

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix   

print('\nClasification report:\n', classification_report(gold_result, test_result))
print('\nConfussion matrix:\n',confusion_matrix(gold_result, test_result))


Clasification report:
               precision    recall  f1-score   support

      advert       0.81      0.83      0.82       107
  non-advert       0.55      0.51      0.53        43

    accuracy                           0.74       150
   macro avg       0.68      0.67      0.68       150
weighted avg       0.73      0.74      0.74       150


Confussion matrix:
 [[89 18]
 [21 22]]


In [22]:
#get precision, recall, f1 for top 3 models

svc_classifier = SVC_classifier.train(labeled_data)
mnb_classifier = MNB_classifier.train(labeled_data)


import sklearn
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix   

test_result = []
gold_result = []

for i in range(len(labeled_data_test)):
    test_result.append(final_classifier.classify(labeled_data_test[i][0]))
    gold_result.append(labeled_data_test[i][1])

print("\nBernoulliNB_classifier:\n")
print('Clasification report:\n', classification_report(gold_result, test_result))
print('\nConfussion matrix:\n',confusion_matrix(gold_result, test_result))


test_result_svc = []
gold_result_svc = []

for i in range(len(labeled_data_test)):
    test_result_svc.append(svc_classifier.classify(labeled_data_test[i][0]))
    gold_result_svc.append(labeled_data_test[i][1])

print("\nSVC_classifier:\n")
print('Clasification report:\n', classification_report(gold_result_svc, test_result_svc))
print('\nConfussion matrix:\n',confusion_matrix(gold_result_svc, test_result_svc))


test_result_mnb = []
gold_result_mnb = []

for i in range(len(labeled_data_test)):
    test_result_mnb.append(mnb_classifier.classify(labeled_data_test[i][0]))
    gold_result_mnb.append(labeled_data_test[i][1])

print("\nMNB_classifier:\n")
print('Clasification report:\n', classification_report(gold_result_mnb, test_result_mnb))
print('\nConfussion matrix:\n',confusion_matrix(gold_result_mnb, test_result_mnb))


C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)



BernoulliNB_classifier:

Clasification report:
               precision    recall  f1-score   support

      advert       0.81      0.83      0.82       107
  non-advert       0.55      0.51      0.53        43

    accuracy                           0.74       150
   macro avg       0.68      0.67      0.68       150
weighted avg       0.73      0.74      0.74       150


Confussion matrix:
 [[89 18]
 [21 22]]

SVC_classifier:

Clasification report:
               precision    recall  f1-score   support

      advert       0.71      1.00      0.83       107
  non-advert       0.00      0.00      0.00        43

    accuracy                           0.71       150
   macro avg       0.36      0.50      0.42       150
weighted avg       0.51      0.71      0.59       150


Confussion matrix:
 [[107   0]
 [ 43   0]]

MNB_classifier:

Clasification report:
               precision    recall  f1-score   support

      advert       0.79      0.75      0.77       107
  non-advert       0.4

C:\Users\User\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
## save final classifier

import pickle
save_classifier = open("sk_Bernoulli.pickle","wb") #binary write
pickle.dump(final_classifier, save_classifier)
save_classifier.close()

#Load the save classifier 
classifier_saved = open("sk_Bernoulli.pickle", "rb") #binary read
classifier_load = pickle.load(classifier_saved)
classifier_saved.close()

#Classify the test data
print(nltk.classify.accuracy(classifier_load, labeled_data_test))


0.74


In [23]:
predicted_labels =[]

for i in all_data_as_dict1:
    lab=final_classifier.classify(i)
    predicted_labels.append(lab)
print(predicted_labels)

['advert', 'non-advert', 'non-advert', 'non-advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'non-advert', 'non-advert', 'non-advert', 'non-advert', 'non-advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'non-advert', 'non-advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'non-advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'non-advert', 'non-advert', 'advert', 'non-advert',

In [29]:
## find misclassified tweet

print ("\t\t\t\tactual label : predicted label")
for count, item in enumerate(label_test):
    tl = item
    pl = predicted_labels[count]
    sent = final1[count]
    if pl != tl:
        print(tl, " != ", pl, " : ", sent)

				actual label : predicted label
advert  !=  non-advert  :  ['good', 'pod', 'upnp', 'nothin', 'c', 'downplaying', 'dhs', 'advisory', 'name', 'researcher']
non-advert  !=  advert  :  ['bos', 'really', 'need', 'staying', 'logged', 'still', 'give', 'look', 'lol']
advert  !=  non-advert  :  ['changing', 'life', 'independent', 'financial', 'advisor', 'india', 'forever', 'india', 'tablet', 'broking', 'financial', 'advisory', 'industry']
advert  !=  non-advert  :  ['music', 'movement', 'feel', 'bad', 'hip', 'fabulous', 'alive']
advert  !=  non-advert  :  ['tell', 'getting', 'rich', 'wall', 'street', 'try', 'others', 'try', 'fearful', 'others', 'greedy']
non-advert  !=  advert  :  ['thing']
non-advert  !=  advert  :  ['isolation', 'big', 'challenge', 'worker', 'affecting', 'morale', 'employee', 'mental', 'health', 'latest', 'article', 'look', 'environment', 'way', 'manager', 'support', 'staff']
non-advert  !=  advert  :  ['stay', 'everybody']
non-advert  !=  advert  :  ['alero', 'improves', 

## prepare scoring data

In [26]:
col_list= ['topic']
score_all = pd.read_csv("data_classification_v2.csv")
score = pd.read_csv("data_classification_v2.csv",usecols=col_list)


In [27]:
print(len(score))
print(score.head())

77856
                                                                                                                                             topic
0  ['great', 'place']                                                                                                                             
1  ['billy', 'porter', 'engaging', 'politically', 'creatively', 'covid', 'daily', 'social', 'distancing', 'show']                                 
2  ['surprising', 'real', 'job']                                                                                                                  
3  ['exciting', 'appen', 'job']                                                                                                                   
4  ['article', 'brought', 'smile', 'face', 'great', 'hear', 'fellow', 'parent', 'thing', 'theyre', 'keep', 'moving', 'forward', 'juggling', 'kid']


In [29]:
#code to convert df to list 

token2 = score['topic'].tolist()
#print(token2)

def convert(lst): 
    return eval(lst)

final2=[]
for i in token2:
    tokenf=convert(i)
    final2.append(tokenf)

#print(final2)

In [45]:
#create  vectors for documents uusing dictionary in training dataset

tweet_vecs_score = docs2vecs(final2, tweet_dictionary)

print(tweet_vecs_score[0:2])

#convert to dict with the term ids given frequency 1
score_data_as_dict = [{id:1 for (id, tf_value) in vec} for vec in tweet_vecs_score]
print(score_data_as_dict[0:2])

[[(410, 1), (606, 1)], [(190, 1), (308, 1), (758, 1), (778, 1), (926, 1), (930, 1)]]
[{410: 1, 606: 1}, {190: 1, 308: 1, 758: 1, 778: 1, 926: 1, 930: 1}]


In [49]:
advert_label=[]

for i in score_data_as_dict:
    label= final_classifier.classify(i)
    advert_label.append(label)
   
print(advert_label)

['advert', 'advert', 'non-advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'non-advert', 'non-advert', 'advert', 'advert', 'non-advert', 'advert', 'non-advert', 'non-advert', 'advert', 'advert', 'non-advert', 'non-advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'non-advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'non-advert', 'non-advert', 'advert', 'advert', 'non-advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'advert', 'non-advert', 'non-advert', 'advert', 'advert',

In [52]:
print(len(advert_label))

label_col = pd.DataFrame(advert_label, columns=['advert_label'])
label_col.head()

77856


advert_label
0  advert     
1  advert     
2  non-advert 
3  advert     
4  non-advert

In [55]:
#join the labels to the maindataset

scored_classification=score_all.join(label_col)

scored_classification.head()

#save to local

scored_classification.to_csv('scored_classification.csv',index=False)

In [62]:
is_advert=scored_classification[scored_classification['advert_label']=='advert']

print("proportion of advert" , len(is_advert)/len(scored_classification), "& number of advert is ", len(is_advert))

print("proportion of non-advert" , 1-(len(is_advert)/len(scored_classification)), '& number of non-advert is', len(scored_classification)-len(is_advert))

proportion of advert 0.7052378750513769 & number of advert is  54907
proportion of non-advert 0.2947621249486231 & number of non-advert is 22949


## combine train, test and score dataset for subsequent topic modelling on non-adverts

In [80]:
total= [scored_classification,comb_train_all,test_all]
combined_data_after_classification = pd.concat(total,sort=False)

print(len(combined_data_after_classification))


pd.set_option('display.max_colwidth', -1)

#print(combined_data_after_classification.head())

combined_data_after_classification.to_csv('combined_data_classified.csv',index=False)

78606


In [85]:
is_not_advert = combined_data_after_classification[combined_data_after_classification['advert_label']=='non-advert']

print("proportion of advert" , 1- len(is_not_advert)/len(combined_data_after_classification), "& number of advert is ", len(combined_data_after_classification)-len(is_not_advert))

print("proportion of non-advert" , (len(is_not_advert)/len(combined_data_after_classification)), '& number of non-advert is', len(is_not_advert))

proportion of advert 0.7040047833498715 & number of advert is  55339
proportion of non-advert 0.2959952166501285 & number of non-advert is 23267


In [84]:

print(is_not_advert.week_num.value_counts())

is_not_advert.to_csv('combined_data_classified(non_advert).csv',index=False)

1    7159
3    5616
2    5494
4    4998
Name: week_num, dtype: int64


## get weekly data

In [88]:
#get weekly data. Change week_num parameter accordingly

is_week2=is_not_advert['week_num']==2
week2=is_not_advert[is_week2]

#print(week2.head())
print(len(week2))
week2.to_csv('classified_week2.csv', sep=',', index=False)

5494
